version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testingdb
      POSTGRES_DB: test
    volumes:
      - ~/Projects/database:/var/lib/postgresql/data
    networks:
      - database
networks:
  database:
    external: true
volumes:
  database:
    driver: local
